apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  labels:
    app: example-app
  annotations:
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 7
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: 661611/python:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "60Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"